$(document).ready(function () {
    var Translations = {
        'login_first': "bạn phải đăng nhập trước",
        'are_you_sure_you_want_to_do_this': "Bạn có chắc chắn muốn thực hiện thao tác này?",
        'results_have_been_saved': 'kết quả đã được lưu',
        'error_saving_test_result': 'xảy ra lỗi khi lưu kết quả của bạn',
        'you_must_login_to_save_test_result': 'để lưu kết quả bạn cần đăng nhập trước',
        'you_must_click_start_test_first': 'trước tiên, hãy bấm Start để bắt đầu test',
        'you_asked_for_answer': 'phải xem đáp án',
        'used': 'sử dụng',
        'attempts': 'lần thử',
        'hints': 'hints',
        'you_are_doing_exam_results_will_be_reset': 'bạn đang làm bài exam. Nếu bạn chuyển đi, kết quả sẽ bị mất. OK?',
        'time_out': 'hết giờ',
        'enrol_now': 'đăng ký',
        'you_did_not_allow_microphone_access': 'bạn không làm đúng thao tác để cho phép sử dụng mic. Vì vậy bạn sẽ không thể làm được bài tập ghi âm này',
        'you_must_choose_a_word_to_record_first': 'bạn phải chọn 1 từ để ghi âm trước. Click vào các từ trên',
        'sending': 'đang gửi',
        'edit': 'sửa',
        'are_you_sure_you_want_to_do_this?': 'bạn có chắc chắn muốn thực hiện thao tác này không?',
        'submit': 'đồng ý',
        'cancel': 'hủy bỏ',
        'operation_successful': 'thao tác thành công',
        'operation_failed': 'thao tác thất bại',
        'passwords_do_not_empty': 'mật khẩu không được rỗng',
        'successful': 'thành công',
        'passwords_do_not_match': 'mật khẩu không khớp',
        'Su': 'Cn',
        'Mo': 'T2',
        'Tu': 'T3',
        'We': 'T4',
        'Th': 'T5',
        'Fr': 'T6',
        'Sa': 'T7',
        "January": 'Tháng 1',
        "February": 'Tháng 2',
        "March": 'Tháng 3',
        "April": 'Tháng 4',
        "May": 'Tháng 5',
        "June": 'Tháng 6',
        "July": 'Tháng 7',
        "August": 'Tháng 8',
        "September": 'Tháng 9',
        "October": 'Tháng 10',
        "November": 'Tháng 11',
        "December": 'Tháng 12',
        'upload_files': 'đăng tải',
        'click_to_select_files_to_upload': 'nhấn vào để chọn file tải lên',
        'upload_file_size_exceeds_the_permitted_level.': 'file bạn vừa đăng tải vượt quá mức cho phép.',
        'limit_file_size_upload:': 'dung lượng giới hạn cho phép đăng tải: ',
        'only_allowed_to_upload_files_xls_or_xlsx' : 'chỉ được phép đăng tải tập tin xls hoặc xlsx.',
        'select' : 'chọn',
        '#district' : 'Quận/Huyện',
        '#school__district' : 'Quận/Huyện',
        '#school__id' : 'Trường'
    };
    Sand.translations = $.extend(Sand.translations, Translations);
});
//'sending' : '<div class="alert alert-success margin-t-15">Woking ...<div>'
